name: heartofthemissioncounseling
favicon: null
layout_spectrum: 0.37415
typography_spectrum: 0.38673
title: Holistic Individual and Couples Therapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#fec62e'
    - '#30411a'
    - '#bca022'
    - '#c1731b'
  brandStrength: 0
  lightness: 0.9479651239234954
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
