name: heartofthemissioncounseling
favicon: null
layout_spectrum: 0.9466613598633558
typography_spectrum: 0.38138851220719516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18731771525926888
  lightness: 0.9479651239234954
  saturation: 0.9840590024832636
  rhythmicContrast: 0.8933802838437259
purpose: []
