name: heartofthemissioncounseling
favicon: null
layout_spectrum: 0.75065
typography_spectrum: 0.38673
title: Holistic Individual and Couples Therapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#fec62e'
    - '#30411a'
    - '#bca022'
    - '#c1731b'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
