name: heartofthemissioncounseling
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5494
title: Holistic Individual and Couples Therapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#fec62e'
    - '#30411a'
    - '#bca022'
    - '#c1731b'
  brandStrength: 0.18731771525926888
  lightness: 0.9479651239234954
  saturation: 0.9840590024832636
  rhythmicContrast: 0.8933802838437259
purpose: []
